# -*- coding: utf-8 -*-
"""heart_failure_predetction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104iOTYakbK4ZXD2aBTI4jdzTl3zcMpdR
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# loading the csv data to a pandas dataframe
data_heart = pd.read_csv('/content/sample_data/data.csv')

data_heart.head()

#checking the missing value
data_heart.isnull().sum()

#Checking the distribution of the Target Variable
data_heart['HeartDisease'].value_counts()

#splitting the features and target
X = data_heart.drop(columns='HeartDisease', axis=1)
Y = data_heart['HeartDisease']

#splitting the data into train and test data
X_train , X_test , Y_train, Y_test = train_test_split( X , Y , test_size=0.2, stratify=Y, random_state=2 )

model = LogisticRegression()

model.fit(X_train , Y_train)

