# -*- coding: utf-8 -*-
"""heart_failure_predection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWwe4Rq6t3kjQIdHR1Z62B9-EYJzBU4c

*   female,negative,ASY,N,DOWN:0
*   male,positive,NAP,NORMAL,LVH,Y,FLAT: 1
*   ATA,ST,UP:2
*   TA:3
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
data = pd.read_csv('/content/heart.csv')

data.head()

label = LabelEncoder()

gender = label.fit_transform(data.Sex)

data['gender']= gender

data.head()

data.head()

chestPain_Type=label.fit_transform(data.ChestPainType)

data['chestPain_Type']= chestPain_Type

data.head()

data['ST_Slope'].value_counts()

data['ECG_RESTING'] = label.fit_transform(data.RestingECG)
data['Exercise_Angina'] = label.fit_transform(data.ExerciseAngina)
data['St_Slope']= label.fit_transform(data.ST_Slope)

data.head()

X = data.drop(["Sex",'ChestPainType','RestingECG','ExerciseAngina','ST_Slope'] ,axis=1)

X.head()

Y= data['HeartDisease']

X_Train , X_Test, Y_Train, Y_Test = train_test_split(X,Y, test_size=0.2, random_state=2, stratify = Y)

from sklearn import svm
model = svm.SVC()

model.fit(X_Train, Y_Train)

pred = model.predict(X_Train)
accuracy = accuracy_score(pred, Y_Train)
print(accuracy)

